# todo: fm - unify space casing
on:
  pull_request:
    # todo: fm - what's synchronize doing here?
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  simple_check:
    runs-on: ubuntu-latest
    # todo: fm - what name should I give it?
    name: ""
    steps:
      # todo: fm - do I need this step - what is it doing
      - name: Checkout
        uses: actions/checkout@v1
        with:
          # todo: fm - remove pre-existing note
          fetch-depth: 1 # shallow clone
      - name: Create Simple Check
        id: simple_check
        uses: ./.github/actions/simple-check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: ${{ github.event.pull_request.number }}
      - name: Get the output time
        run: echo "The time was ${{ steps.simple_check.outputs.time }} --" && echo ${{ steps.simple_check.outputs.labels }}
