on:
  push:
    branches:
      - "*"
jobs:
  simple_check:
    runs-on: ubuntu-latest
    name:
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: Create Simple Check
        uses: ./.github/actions/simple-check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
