# todo: fm - change file name
# todo: fm - unify space casing
on:
  pull_request:
    # todo: fm - what's synchronize doing here?
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  # todo: fm - change name
  "Qa Label Check":
    runs-on: ubuntu-latest
    # todo: fm - what name should I give it?
    name: ""
    steps:
      # todo: fm - do I need this step - what is it doing
      - name: Checkout
        uses: actions/checkout@v1
        with:
          # todo: fm - remove pre-existing note
          fetch-depth: 1 # shallow clone
        # todo: fm - change name
      - name: Create Simple Check
        # todo: fm - id needed?
        id: simple_check
        uses: ./.github/actions/simple-check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: ${{ github.event.pull_request.number }}
      # todo: fm - change name
      - name: Print Success
        # todo: fm - ensure correct final output
        run: echo "The labels for pull request ${{ github.event.pull_request.number }} are ${{ steps.simple_check.outputs.labels }}. Action successful."
